KS-2-3 решение задания
pozekyn1test/KotlinSprint pull request #8
Opened 2024-01-24 20:13 UTC by pozekyn1test

2024-01-24 20:30 UTC, ievetrovdev requested changes

2024-01-24 20:30 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/lesson_2_task3.kt
> +    val NUMBER_OF_MINUTES = 60
Небольшая путаница произошла у тебя: по стилю написания - это константа, но они объявляются вне тела main и перед переменной добавляется слово "const"

2024-01-25 11:00 UTC, ievetrovdev approved these changes

2024-01-25 11:00 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/lesson_2_task3.kt
> +    val departureTime = 579
На будущее, если в условии даны конкретные данные, их надо заносить в переменные и потом производить все расчеты, т.е. 
Перевести 9:39 в минуты от начала дня
Прибавить минуты на дорогу
Перевести результат обратно во время

2024-01-25 12:27 UTC, pozekyn1test commented on src/main/kotlin/lesson_2/lesson_2_task3.kt
> +    val departureTime = 579
@ievetrovdev а в итоговом решении все соответствует тому, что написано в комментарии или нет? Мне просто кажется, что да, но вдруг ошибаюсь

2024-01-25 17:35 UTC, merged